name: Documentation typo
description: Found a typo in the documentation? You can use this one!
labels: ["📄 aspect: text"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A brief description of the question or issue, also include what you tried and what didn't work
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: Please add screenshots if applicable
    validations:
      required: false
  - type: textarea
    id: extrainfo
    attributes:
      label: Additional information
      description: Is there anything else we should know about this issue?
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        You can also join the Discord community [here](https://discord.com/invite/47vQN9Z3XB)
        Feel free to check out other cool repositories of the CodeVisors Community [here](https://github.com/codevisors)
